# Here is the GitHub Actions workflow file for deploying the project on Raspberry Pi

name: Deploy to Raspberry Pi
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run deploy script
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh
