# Here is the GitHub Actions workflow file for deploying the project on Raspberry Pi

name: Deploy to Raspberry Pi
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.66.0

      # test connection
      - name: Ping Raspberry Pi
        run: |
          tailscale status
        continue-on-error: true 
      
      # creat file in /home/mmoreira/app/test.txt to test connection
      - name: Test Connection to Raspberry Pi
        run: |
          ssh -o "StrictHostKeyChecking=no" ${{ secrets.RASPBERRY_PI_USER }}@${{ secrets.RASPBERRY_PI_IP }} "'echo "
            Connection Successful" > /home/${{ secrets.RASPBERRY_PI_USER }}/app/test.txt'
          "
        continue-on-error: false
      
      # - name: Deploy to Raspberry Pi
      #   run: |  
      #     scp -o "StrictHostKeyChecking=no" -r ./src/* pi@${{ secrets.RPI_TAILSCALE_IP }}:/home/pi/osuc_digital_twin/src/
      #     ssh -o "StrictHostKeyChecking=no" pi@${{ secrets.RPI_TAILSCALE_IP }} 'bash -s' < ./deploy_script.sh 
          
