# Here is the GitHub Actions workflow file for deploying the project on Raspberry Pi

name: Deploy to Raspberry Pi
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          cd ~/app

          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate
          python -m pip install --upgrade pip
          cd ~/actions-runner/_work/osuc_digital_twin/osuc_digital_twin
          pip install -r requirements.txt
      
      - name: Run deploy script
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh
