# Here is the GitHub Actions workflow file for deploying the project on Raspberry Pi

name: Deploy to Raspberry Pi
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.66.0

      # test connection
      - name: Ping Raspberry Pi
        run: tailscale ping ${{ secrets.RPI_TAILSCALE_IP }}
        continue-on-error: true 
      - name: Deploy to Raspberry Pi
        run: |  
          scp -o "StrictHostKeyChecking=no" -r ./src/* pi@${{ secrets.RPI_TAILSCALE_IP }}:/home/pi/osuc_digital_twin/src/
          ssh -o "StrictHostKeyChecking=no" pi@${{ secrets.RPI_TAILSCALE_IP }} 'bash -s' < ./deploy_script.sh 
          